-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 27, 2018 at 08:14 AM
-- Server version: 10.1.29-MariaDB
-- PHP Version: 7.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `manilaoutdoors`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin_accounts`
--

CREATE TABLE `admin_accounts` (
  `admin_id` int(11) NOT NULL,
  `admin_username` varchar(255) NOT NULL,
  `admin_password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin_accounts`
--

INSERT INTO `admin_accounts` (`admin_id`, `admin_username`, `admin_password`) VALUES
(1, 'admin', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220');

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `category_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `category_name`) VALUES
(1, 'Apparel'),
(2, 'Backpacks'),
(3, 'Tents'),
(4, 'Hiking Gears'),
(5, 'Hammocks'),
(6, 'Sleeping Gears');

-- --------------------------------------------------------

--
-- Table structure for table `customers`
--

CREATE TABLE `customers` (
  `id` int(11) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `street_address` varchar(255) NOT NULL,
  `barangay` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `province` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `contact_number` varchar(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `customers`
--

INSERT INTO `customers` (`id`, `first_name`, `last_name`, `email`, `username`, `password`, `street_address`, `barangay`, `city`, `province`, `country`, `contact_number`) VALUES
(1, 'John Ray', 'Pantaleon', '', 'johnray016', '7110eda4d09e062aa5e4a390b0a572ac0d2c0220', '744 Tantiongco St.', 'San Guillermo', 'Morong', 'Rizal', 'Philippines', '09353137125');

-- --------------------------------------------------------

--
-- Table structure for table `order_details`
--

CREATE TABLE `order_details` (
  `invoice_number` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `date_ordered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quantity_ordered` smallint(6) NOT NULL,
  `payment_id` int(11) NOT NULL,
  `customers_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `payment_details`
--

CREATE TABLE `payment_details` (
  `payment_id` int(11) NOT NULL,
  `payment_details` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `payment_details`
--

INSERT INTO `payment_details` (`payment_id`, `payment_details`) VALUES
(1, 'Paypal'),
(2, 'Maestro'),
(3, 'Dragon Pay'),
(4, 'VISA');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `product_ID` int(11) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `sku` varchar(255) NOT NULL,
  `short_description` text NOT NULL,
  `long_description` text NOT NULL,
  `features` text NOT NULL,
  `price` decimal(65,2) NOT NULL,
  `quantity` smallint(6) NOT NULL,
  `image` varchar(255) NOT NULL,
  `meta_title` varchar(255) NOT NULL,
  `meta_description` varchar(255) NOT NULL,
  `meta_keyword` varchar(255) NOT NULL,
  `category_ID` int(11) NOT NULL,
  `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_ID`, `product_name`, `sku`, `short_description`, `long_description`, `features`, `price`, `quantity`, `image`, `meta_title`, `meta_description`, `meta_keyword`, `category_ID`, `date_created`) VALUES
(1, 'Osprey Daylite Plus 20L Travel Pack Beryl Blue', 'OSPREY-407-BB', '<p>Traveling can be difficult but the Daylite makes it easier. With protected, padded storage for a laptop, and just enough organization to keep you moving through the terminal, it\'s the travel companion you never leave behind.</p>', '<p>The Daylite Series started out with humble beginnings, a simple accessory to attach to our larger packs. However, its lightweight, simplicity, durability, comfortable carry and price has proven to be wildly popular, and today their popularity is undeniable. While the Daylite and Daylite Plus continue to serve well as add-on packs for traveling and more, they shine on their own with incredible versatility and are now available in an even more robust color palette than before.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Main</strong> - 210D Nylon Double Diamond Ripstop</p>\r\n<p><strong>Accent</strong> - 400HD Nylon Packcloth</p>\r\n<p><strong>Bottom</strong> - 400HD Nylon Packcloth</p>\r\n', '<strong><p class=\"orange\">Features</p></strong> <ul> <li>Large panel-loading main compartment</span></li> <li>Attaches to a variety of compatible Osprey packs</span></li> <li>Side mesh pockets</span></li> <li>Front pocket with mesh organizer and key clip</span></li> <li>Spacermesh shoulder straps with integrated handle</span></li> <li>Multi-function interior sleeve for hydration or tablet</span></li> <li>Mesh-covered backpanel with slotted foam</span></li> </ul>', '3250.00', 2, 'assets/img/products/Osprey_Daylite_Plus_20L_Travel_Pack_Beryl_Blue_1.jpg\r\n', 'Osprey Daylite Plus 20L Travel Pack Beryl Blue', 'Traveling can be difficult but the Osprey Daylite Plus 20L Travel Pack makes it easier', 'osprey, hiking, manila outdoors, backpack', 2, '2018-01-26 08:24:44'),
(2, 'Ticket to the moon Double Hammock Turquoise / Green', 'TMD1411', '<p>Ticket to the Moon make leight travel hammocks of parachute silk. This breathable nylon dries fast and can be washed. The hammock is packed in a small pouch which is sewed on the hammock and can also be used to put small things in it.</p>', '<p>That is the freedom of today. No luxury, no time planner, only nature, your hammock and you. And if you are on the road \r\nyou appreciate leight luggage. That is why the Ticket to the Moon founder had the idea to create a light weight travel hammock. \r\nThe result are today\'s Ticket to the Moon travel hammocks made of parachute silk. This functional material is not only light but \r\nalso breathable, soft to the skin and washable. You can take this Ticket to the Moon light hammock everywhere, for the holidays, a weekend trip or on a boat for instance. Carrying bag included.</p>\r\n\r\n<strong><p class=\"orange\">Specifications:</p></strong>\r\n<p><strong>Load Capacity: </strong>200 kg - 440 lbs<br></p>\r\n<p><strong>Color: </strong>Turquoise / Green<br></p>\r\n<p><strong>Weight: </strong>600 g/1.3 lbs<br></p>\r\n<p><strong>Dimensions: </strong>320 x 200 cm/10.5 x 6.5 ft<br></p>\r\n', ' <strong><p class=\"orange\">Features:</p></strong>  <ul> <li>The parachute hammock was made by travellers for travellers. </li> <li>A comfortable sleep and ideal protection from insects and small reptiles. </li> <li>It can replace your tent: lightweight, strong, and foldable.</li> <li>The hammock sets up in less than a minute. </li> <li>Is rot-resistant and quick to dry (machine washable 30Â°C). </li> <li>Ideal for camping, trekking and any outdoor activities.</li> </ul>', '3200.00', 12, 'assets/img/products/Ticket_to_the_moon_Double_Hammock_Turquoise_Green_1.jpg', 'Ticket to the moon Double Hammock Turquoise / Green', 'Ticket to the Moon make leight travel hammocks of parachute silk. This breathable nylon dries fast and can be washed. The hammock is packed in a small pouch which is sewed on the hammock and can also be used to put small things in it.', 'hammock, ticket to the moon, manila outdoors, sleeping gear, camping gear', 5, '2018-01-26 08:26:00'),
(3, 'Craghoppers Kimba Lite Men\'s Jacket - Royal Navy', 'CMW694-RN', '<p>The Kimba jacket is constructed from a highly durable yet breathable fabric with Craghoppers innovative AquaDry membrane technology for an optimal performance in all weather conditions. </p>', '<strong><p class=\"orange\">Specifications:</p></strong>\r\n<p><strong>Color:</strong> Royal Navy<br></p>\r\n<p><strong>Weight:</strong> 750 g<br></p>\r\n\r\n<p class=\"orange\"><strong>Please refer to the images for the sizing guide</strong></p>\r\n<img src=\"assets/img/catalog/craghoppers-sizing-guide.jpg\" class=\"img-responsive\">\r\n', '<strong><p class=\"orange\">Features:</p></strong> <ul> <li>Waterproof, windproof,breathable Aquadry</li> <li>fabric</li> <li>Stylish cut</li> <li>Reflective trim</li> <li>Drawcorded hood</li> <li>Zippered pockets</li> <li>Hem Drawcord</li> <li>Map pocket</li> <li>Hook and Loop adjustable cuffs</li> <li>Packable</li> </ul>', '7300.00', 0, 'assets/img/products/Craghoppers_Kimba_Lite_Mens_Jacket_Royal_Navy_1.jpg', 'Craghoppers Kimba Lite Men\'s Jacket - Royal Navy', 'The Craghoppers Kimba Lite Men\'s Jacket - Royal Navy is constructed from a highly durable yet breathable fabric with Craghoppersâ€™s innovative AquaDry membrane technology for an optimal performance in all weather conditions. ', 'craghoppers, kimba, kimba jacket, hiking apparel, manila outdoors', 1, '2018-01-26 08:30:00'),
(4, 'Vargo Titanium Spoon / Fork / Knife Set', 'T-216', '<p>Slightly lighter than our standard campware set, the ULV version features a matte finish and narrow design.</p>', '<p>The Vargo Titanium Spoon/Fork/Knife Set - ULV (U.ltra L.ight V.ersion) features a smaller, narrower design to make them lighter than our standard Titanium Spoon/Fork/Knife Set.</p>\r\n\r\n<strong><p class=\"orange\">Specifications:</p></strong>\r\n<p><strong>Weight: </strong>38 grams <br></p>\r\n<p><strong>Size: </strong>15.2cm </p>\r\n\r\n\r\n', '<strong><p class=\"orange\">Features:</p></strong> <ul> <li>Matte finish</li> <li>Made of pure titanium</li> <li>Biocompatible</li> <li>Lighter than Lexan utensils</li> <li>Each piece weighs less than 0.5 ounces (14 grams)</li> <li>Mini carabiner included</li> </ul>', '1600.00', 24, 'assets/img/products/Vargo_Titanium_Spoon_Fork_Knife_Set_1.jpg', 'Vargo Titanium Spoon / Fork / Knife Set', 'Slightly lighter than our standard campware set, the Vargo Titanium Spoon / Fork / Knife Set version features a matte finish and narrow design.', 'vargo, hiking, camping cutlery, spoon, fork', 4, '2018-01-26 08:33:41'),
(10, 'Ferrino Backpack Triolet 32+5 Blue', '75581CBB', '<p>4 season mountaineering backpack equipped with all technical details for that activity, front access</p>', '<p>Mountaineering backpack with special technical and ergonomic features which makes it a product of outstanding quality appropriate for every mountaineering activity.</p> \r\n<strong><p class=\"orange\">Specifications</p></strong> \r\n<p><strong>Color: </strong> Blue</p>\r\n<p><strong>Capacity: </strong> 32+5L</p>\r\n<p><strong>Minimum Weight: </strong> 1000 g</p>\r\n<p><strong>Maximum Weight: </strong> 1500 g</p>\r\n', ' <strong><p class=\"orange\">Fabrics</p> </strong> <ul>   <li>420D HD invisible ripstop</li>   <li>Reinforcement in Hypalon </li> </ul>  <strong><p class=\"orange\">Carrying System</p></strong> <ul>   <li>ACT back</li>   <li>Removable back panel reinforced by an adjustable duralluminium bar</li>   <li>Upper adjustment for shoulder straps</li>   <li>Padded and ergonomic shoulder straps and waist band in breathable mesh fabric</li>   <li>Waist band with removable wings to be used with climbing harness </li></ul><strong><p class=\"orange\">Pockets</p></strong> <ul>   <li>Pocket onlid</li>   <li>Safety pocket</li>   <li>Small pocket on waist band</li>   <li>Side pockets in mesh fabric</li>   <li>Shovel/probe holder pocket </li> </ul>  <strong><p class=\"orange\">Accessories</p></strong><ul> <li>Front access to the backpack main compartment</li> <li>Extensible body &#40;+5 l&#41;</li> <li>Ski holders on the sides</li> <li>Two ice axe holders</li> <li>Loops to hold gears on the outside, inside and on waist band</li> <li>Side compression straps</li> <li>Strap to hold rope on lid</li> <li>Compatible with H2 bag</li> <li>Removable straps to hold snow shoes/snow board</li> <li>Chest strap with emergency whistle</li> <li>SOS instructions</li></ul>', '6500.00', 5, 'assets/img/products/ferrino-backpack-triolet-32-5-blue.jpg', 'Ferrino Backpack Triolet 32+5 Blue', 'Ferrino Backpack Triolet 32+5 Blue is a 4 season mountaineering backpack equipped with all technical details for that activity, front access', 'ferrino, backpack, hiking, mountaineering, rucksack', 2, '2018-01-26 17:22:42'),
(11, 'Ferrino Sleepingbag Yukon Plus', '86357BBD', '<p>Made with filling in H.T.F. High Thermal Perfomance for its high performance that comes from a blend of two hollow fibers with different characteristics.</p>', '<strong><p class=\"orange\">Specifications</p> </strong>\r\n<p><strong>EXT.: </strong> 100% Polyester 210T Ripstop</p>\r\n<p><strong>INNER: </strong> Polyester Pongee 240T</p>\r\n<p><strong>FILLING: </strong> 200 g/m2 HTF Perfomance &#40;2 layers&#41;</p> \r\n\r\n', '<strong><p class=\"orange\">Features</p></strong><ul> <li>Cold protection hood </li> <li>Zip baffle and padded heat collar </li> <li>2-way combinable zips </li> <li>Two ice axe holders</li> <li>Storage pocket </li> <li>Offset seams: to prevent heat dispersion,<br>the seams between the inner and outer layers are never communicating</li> <li>Sack with double protection closure/extension. </li></ul>', '3100.00', 4, 'assets/img/products/ferrino-sleepingbag-yukon-plus.jpg', 'Ferrino Sleepingbag Yukon Plus', 'Ferrino Sleepingbag Yukon Plus is made with filling in H.T.F. High Thermal Perfomance for its high performance that comes from a blend of two hollow fibers with different characteristics.', 'ferrino, sleeping bag, camping hiking, manila outdoors', 6, '2018-01-26 17:29:37'),
(12, 'Ferrino Fitzroy Backpack 22L Black', '75580CCC', '<p>4 seasons mountaineering backpack equipped with RECCO reflector</p>', '<p>Multipurpose backpack, equipped with many accessories, appropriate for all mountaineering activities.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Weight: </strong> 1100 g</p>\r\n<p><strong>Capacity: </strong> 22L</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>420D HD invisible ripstop</li>\r\n  <li>Supertex®  </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Carrying System</p></strong>\r\n<ul>\r\n  <li>D.E.A. Back panel</li>\r\n  <li>Ultra-breathable back in mesh fabric</li>\r\n  <li>Upper adjustment for shoulder straps</li>\r\n  <li>Ergonomic, padded and quilted shoulder straps and waist belt in breathable mesh fabric</li>\r\n  <li>Load lifter </li>\r\n</ul>\r\n<strong><p class=\"orange\">Pockets</p></strong>\r\n<ul>\r\n  <li>Double pocket in top lid</li>\r\n  <li>Security pocket</li>\r\n  <li>Front and side bellows pockets</li>\r\n  <li>Pocket in waist belt</li>\r\n  <li>Inside pocket in back</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accesssories</p></strong>\r\n<ul>\r\n  <li>Front access to main backpack compartment</li>\r\n  <li>Double bellows bottom with front access</li>\r\n  <li>Removable top lid that converts to a small backpack</li>\r\n  <li>Side compression tapes</li>\r\n  <li>Two ice axe/pole holders</li>\r\n  <li>Removable gear straps on bottom</li>\r\n  <li>Loops in top lid</li>\r\n  <li>Backpack cover</li>\r\n  <li>Compatible with H2 bag hydration control system</li>\r\n</ul>', '9800.00', 5, 'assets/img/products/ferrino-fitzroy-22-black.jpg', 'Ferrino Fitzroy Backpack 22L Black', 'Ferrino Fitzroy 22 Black is a 4 seasons mountaineering backpack equipped with RECCO reflector', 'ferrino, fitzroy, backpack, rucksack', 2, '2018-01-26 18:27:53'),
(13, 'Ferrino Backpack Finisterre 48 Black', '75735BRR', '<p>Linear backpack complete with all equipment. The D.N.S back is a guarantee of perfect ventilation.</p>', '<p>Ideal backpack for excursions, it has a slim shape and it is equipped with all accessories. D.N.S. dry net system allows for perfect ventilation of your back.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Weight: </strong> 1650 g</p>\r\n<p><strong>Capacity: </strong> 48 L</p>', '\r\n<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Diamond HD</li>\r\n  <li>Supertex® </li>\r\n  <li>Dupont Hypalon® reinforcements </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Carrying System</p></strong>\r\n<ul>\r\n  <li>D.N.S. back</li>\r\n  <li>Load lifter</li>\r\n  <li>Upper adjustment for shoulder straps</li>\r\n  <li>Ergonomic, padded and quilted shoulder straps and waist belt in breathable mesh fabric</li>\r\n  <li>Load lifter </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Pockets</p></strong>\r\n<ul>\r\n  <li>Pocket in top lid</li>\r\n  <li>Safety pocket</li>\r\n  <li>Bellows front pocket</li>\r\n  <li>Bellows side pockets</li>\r\n  <li>Pocket on waist belt</li>\r\n  <li>Back side inner pocket</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accesssories</p></strong>\r\n<ul>\r\n  <li>Folding double bottom with front access</li>\r\n  <li>Compression straps</li>\r\n  <li>Two ice-axe/stick holder</li>\r\n  <li>Compatible with the H2 bag hydration control system</li>\r\n  <li>Loops on top lid</li>\r\n  <li>Removable straps for snowshoes/snowboard</li>\r\n  <li>Loops in top lid</li>\r\n  <li>Backpack cover</li>\r\n  <li>Removable gear straps on the bottom</li>\r\n</ul>', '5200.00', 6, 'assets/img/products/ferrino-backpack-finisterre-48-black.jpg', 'Ferrino Backpack Finisterre 48 Black', 'Ferrino Backpack Finisterre 48 Black is a inear backpack complete with all equipment. The D.N.S back is a guarantee of perfect ventilation.', 'ferrino, fitzroy, rucksack, manila outdoors', 2, '2018-01-26 18:39:18'),
(14, 'Osprey Aether Anti-Gravity 70L Rucksack', '10000688-AD-M', '<p>Winner of Outside Magazine\'s Gear of the Year Award for 2017, the Aether AG™ 70 is the perfect backpacking solution when your primary concerns are carrying heavy loads in ventilated comfort for bigger trips and weeklong-plus excursions. Now featuring our innovative Anti-Gravity™ technology and custom fit along with an incredibly robust feature set and a top lid that converts to a functional daypack or summit pack.</p>', '<p>For backpacking, thru-hikes and alpine expeditions, the Aether AG™ Series has a pedigree like no other pack. We set the bar for technical backpacking packs by combining Anti-Gravity™ technology with customizable fit and innovative features to create a more capable and comfortable pack for long-haul load carrying on any multi-day excursion.When you need a pack that can carry heavy loads for up to a week or more, there is no better option than the Aether AG™ 70. Size XL comes with a Large hipbelt and harness.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Adirondack Green</p>\r\n<p><strong>Weight: </strong> 2365 g</p>\r\n<p><strong>Capacity: </strong> 70 L</p>\r\n<p><strong>Dimensions: </strong> 85 x  40 x 34 cm</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Built in Raincover</li>\r\n  <li>Dual upper side compression straps</li>\r\n  <li>Dual access side stretch mesh pockets</li>\r\n  <li>Lower Inside-Out™ compression straps</li>\r\n  <li>Zippered hipbelt pockets</li>\r\n  <li>Stow-on-the-Go™ trekking pole attachment</li>\r\n  <li>Additional main compartment access</li>\r\n  <li>Large stretch mesh front panel pocket</li>\r\n  <li>Dual front compression straps with StraightJacket™ compression</li>\r\n  <li>Dual ice tool loops with bungee tie-offs</li>\r\n  <li>Zippered sleeping bag compartment with removable divider</li>\r\n  <li>Removable sleeping pad straps</li>\r\n  <li>Integrated FlapJacket™ cover for lidless use</li>\r\n  <li>Internal hydration reservoir sleeve</li>\r\n  <li>Large front J-zip access to main compartment</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Fabric</p></strong>\r\n<ul>\r\n  <li>210D Nylon Dobby</li>\r\n  <li>210D High Tenacity Nylon Shadow Box</li>\r\n  <li>500D Nylon Packcloth</li>\r\n</ul>', '17300.00', 2, 'assets/img/products/osprey-aether-anti-gravity-70l-rucksack.jpg', 'Osprey Aether Anti-Gravity 70L Rucksack', 'Osprey Aether Anti-Gravity 70L Rucksack is the perfect backpacking solution when your primary concerns are carrying heavy loads for weeklong-plus excursions.', 'osprey, aether, anti-gravity, rucksack, backpack', 2, '2018-01-26 19:18:10'),
(15, 'Osprey Stratos 24L Hiking Backpack Black', '10000812-BK', '<p>Like carrying a breeze on your back, this incredibly ventilated pack features panel-loading convenience and organization for demanding day hikes and features adjustable torso lengths to dial in the perfect fit for everyone.</p>', '<p>The supremely ventilated, featured and durable Stratos Series receives a makeover that is more than skin deep for Spring 2017. Now featuring adjustable torso lengths for improved fit and comfort with updated aesthetics, the Stratos 24 is the go-to choice for those who prefer panel-loading organization on day hikes in wet or hot environments where staying dry and keeping your cool matter most. When the weather turns, fear not - Stratos keeps your gear and pack protected with an integrated raincover. Smartly organized pocketing keeps all your equipment where you need it, when you need.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Black</p>\r\n<p><strong>Weight: </strong> 1250 g</p>\r\n<p><strong>Capacity: </strong> 24 L</p>\r\n<p><strong>Dimensions: </strong> 59 x 30 x 30 cm</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Front panel storage pocket</li>\r\n  <li>Front panel vertical center zippered pocket</li>\r\n  <li>Large top panel zippered slash pocket</li>\r\n  <li>Dual side compression straps</li>\r\n  <li>Stow-on-the-Go&trade; trekking pole attachment</li>\r\n  <li>Dual side stretch mesh pockets</li>\r\n  <li>Ice tool loop with bungee tie-off</li>\r\n  <li>Integrated raincover</li>\r\n  <li>Zippered hipbelt pockets</li>\r\n  <li>Internal hydration reservoir sleeve</li>\r\n  <li>Dual-zippered panel access to main compartment</li>\r\n  <li>Large top panel zippered slash pocket</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Fabric</p></strong>\r\n<ul>\r\n  <li>Main: 210D Nylon Crosshatch</li>\r\n  <li>Accent: 420HD Nylon Packcloth</li>\r\n  <li>Bottom: 420HD Nylon Packcloth</li>\r\n</ul>', '8200.00', 3, 'assets/img/products/osprey-stratos-24l-hiking-backpack-black.jpg', 'Osprey Stratos 24L Hiking Backpack Black', 'Osprey Stratos 24L Hiking Backpack Black features panel-loading convenience and organization for demanding day hikes', 'Hiking, backpack, rucksack, daypack, osprey, stratos', 2, '2018-01-26 19:39:34'),
(16, 'Osprey Daylite Plus 20L Travel Pack Real Red', '10000407-RR', '<p>Traveling can be difficult but the Daylite makes it easier. With protected, padded storage for a laptop, and just enough organization to keep you moving through the terminal, it\'s the travel companion you never leave behind.</p>', '<p>The Daylite Series started out with humble beginnings, a simple accessory to attach to our larger packs. However, its lightweight, simplicity, durability, comfortable carry and price has proven to be wildly popular, and today their popularity is undeniable. While the Daylite and Daylite Plus continue to serve well as add-on packs for traveling and more, they shine on their own with incredible versatility and are now available in an even more robust color palette than before.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Real Red</p>\r\n<p><strong>Weight: </strong> 453 g</p>\r\n<p><strong>Capacity: </strong> 20 L</p>\r\n<p><strong>Dimensions: </strong> 45.7 x  25.4 x 22.9 cm</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Large panel-loading main compartment</li>\r\n  <li>Attaches to a variety of compatible Osprey packs</li>\r\n  <li>Side mesh pockets</li>\r\n  <li>Front pocket with mesh organizer and key clip</li>\r\n  <li>Spacermesh shoulder straps with integrated handle</li>\r\n  <li>Multi-function interior sleeve for hydration or tablet</li>\r\n  <li>Mesh-covered backpanel with slotted foam</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Fabric</p></strong>\r\n<ul>\r\n  <li>Main: 210D Nylon Double Diamond Ripstop</li>\r\n  <li>Accent: 400HD Nylon Packcloth</li>\r\n  <li>Bottom: 400HD Nylon Packcloth</li>\r\n</ul>', '3300.00', 5, 'assets/img/products/osprey-daylite-plus-20l-travel-pack-real-red.jpg', 'Osprey Daylite Plus 20L Travel Pack Real Red', 'Traveling can be difficult but the Osprey Daylite Plus 20L Travel Pack Real Red makes it easier  with protected, padded storage for a laptop, and just enough organization.', 'laptop backpack, osprey, daylite plus, travel pack', 2, '2018-01-26 19:52:24'),
(17, 'Osprey Farpoint 40L M/L Travel Pack Volcanic Grey', '10000298-VG', '<p>Osprey’s Farpoint 40 is perfect for a weekend getaway in the city or the wilderness. The LightWire™ frame suspension transfers the load from harness to hipbelt. A mesh backpanel improves ventilation and the mesh on the harness and hipbelt reduces chafing under load. The entire suspension stows away under a zippered panel creating a sleek silhouette for transport. </p>', '<p>Unzip the lockable sliders to access the main compartment. Inside there’s a mesh pocket for small items. Dual compression straps keep cargo from shifting during transit. </p>\r\n\r\n<p>Outside you’ll find a zippered front panel slash pocket to keep you organized and sewn attachment points to lash on extra gear. No matter how much you choose to carry, StraightJacket™ compression straps stabilize the load. The padded top and side handles give you purchase when you need to toss the Farpoint 40 into the back of the bus.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Volcanic Grey</p>\r\n<p><strong>Weight: </strong> 1438 g</p>\r\n<p><strong>Capacity: </strong> 40 L</p>\r\n<p><strong>Dimensions: </strong> 53 x 33 x 23 cm</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Fixed, unisex backpanel, hipbelt and harness system can easily be stowed and zipped away for a slimmer profile when traveling. The creates a slimmer profile for the bag, making it a better checked bag</li>\r\n  <li>Large panel zip access to main compartment with lockable sliders provides accessibility and security to main contents </li>\r\n  <li>Top and side padded carry handles are helpful when you need to hoist the pack</li>\r\n  <li>Dual front compression straps keep gear stable while wearing the pack</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Fabric</p></strong>\r\n<ul>\r\n  <li>Main: 210D Nylon Mini Hex Diamond Ripstop</li>\r\n  <li>Accent: 600D Packcloth</li>\r\n  <li>Bottom: 600D Packcloth</li>\r\n</ul>', '8200.00', 4, 'assets/img/products/osprey-farpoint-40l-m-l-travel-pack-volcanic-grey.jpg', 'Osprey Farpoint 40L M/L Travel Pack Volcanic Grey', 'Osprey Farpoint 40L M/L Travel Pack Volcanic Grey is perfect for a weekend getaway in the city or the wilderness.', 'osprey, farpoint, travelpack, backpack', 2, '2018-01-26 19:55:55'),
(18, 'Ferrino Backpack Transalp 100 Red', '75691RR', '<p>Hardwearing, multi-pocket trekking backpack with front access to the main compartment.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Red</p>\r\n<p><strong>Weight: </strong> 2650 g</p>\r\n<p><strong>Capacity: </strong> 100 L</p>\r\n<p><strong>Dimensions: </strong> 85 x 52 x 40 cm</p>\r\n', '<strong><p class=\"orange\">Fabric</p></strong>\r\n<ul>\r\n  <li>Jacquard Weave 500D</li>\r\n  <li>Supertex® </li>\r\n  <li>Reinforcements in DuPontTM Hypalon®</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Carrying System</p></strong>\r\n<ul>\r\n  <li>D.E.A. back</li>\r\n  <li>Super-breathable back in mesh fabric</li>\r\n  <li>Shoulder straps with load lifter</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Pockets</p></strong>\r\n<ul>\r\n  <li>Double pocket in top lid</li>\r\n  <li>Safety pocket</li>\r\n  <li>Side pockets</li>\r\n  <li>Mesh front pocket</li>\r\n  <li>Mesh side pockets</li>\r\n  <li>Pockets on waist belt</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accesssories</p></strong>\r\n<ul>\r\n  <li>Folding double bottom with front access</li>\r\n  <li>Front access to the main backpack compartment</li>\r\n  <li>Front compression straps</li>\r\n  <li>Two ice-axe/stick holder</li>\r\n  <li>Gear straps on the bottom</li>\r\n  <li>Loops on top lid</li>\r\n  <li>Removable backpack cover</li>\r\n  <li>Compatible with the H2 bag hydration control system</li>\r\n</ul>', '9800.00', 7, 'assets/img/products/ferrino-backpack-transalp-100-red.jpg', 'Ferrino Backpack Transalp 100 Red', 'Ferrino Backpack Transalp 100 Red is a hardwearing, multi-pocket trekking backpack with front access to the main compartment.', 'ferrino, backpack, rucksack, transalp, hiking', 2, '2018-01-26 20:05:39'),
(19, 'Ferrino Bercy 30 Blue Backpack', '75802BBB', '<p>Multipurpose backpack with padded back and multiple pockets for perfect organization. Padded pocket for notebook and fast access from the back</p>', '<p>Multipurpose backpack with padded back and multiple pockets for perfect organization. Padded pocket for notebook and fast access from the back</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Blue</p>\r\n<p><strong>Weight: </strong> 550 g</p>\r\n<p><strong>Capacity: </strong> 30 L</p>', '<strong><p class=\"orange\">Fabric</p></strong>\r\n<ul>\r\n  <li>Polyester Dobby 420D</li>\r\n  <li>Polyester Invisible ripstop 210D</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Carrying System</p></strong>\r\n<ul>\r\n  <li>Padded and quilted back in breathable mesh fabric</li>\r\n  <li>Ergonomic shoulder straps padded with breathable mesh fabric</li>\r\n  <li>Waist belt with removable strap</li>\r\n  <li>Removable chest strap</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Pockets</p></strong>\r\n<ul>\r\n  <li>Front pocket</li>\r\n  <li>Mesh side pockets</li>\r\n  <li>Organizer inside</li>\r\n  <li>Padded pocket to store tablet with quick access from the back</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accesssories</p></strong>\r\n<ul>\r\n  <li>Carrying handle</li>\r\n  <li>Compression straps</li>\r\n  <li>Internal compression straps to fasten the notebook</li>\r\n  <li>External straps for additional gears</li>\r\n</ul>', '2500.00', 3, 'assets/img/products/ferrino-bercy-30-blue.jpg', 'Ferrino Bercy 30 Blue Backpack', 'Ferrino Bercy 30 Blue is a multipurpose backpack with padded back and multiple pockets for perfect organization. Padded pocket for notebook and fast access from the back.', 'ferrino, bercy, travel pack, backpack, multipurpose backpack', 2, '2018-01-26 20:12:06'),
(20, 'Merrel Women\'s Siren Q2 Strap Sandal', 'M-0037492', '<p>This women\'s strap-in is specifically engineered for female power-houses. Designed for women, the Siren Q2 Strap gives you support, alignment and stability, so you can forge your own path and embrace the great outdoors!</p>', '<p>Its Merrell In-Board Compression molded EVA footframe and Textured EVA Integrated footbed provides cushioning for complete support and comfort on the longest of days and over diverse terrain. The Siren Q2 Strap\'s dual-density midsole with heel-centering technology provides gender engineered alignment and comfort.</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Waterproof nubuck and webbing upper makes this shoe perfect for rain or shine</li>\r\n  <li>Lycra® neoprene lining for padded comfort </li>\r\n  <li>Q FORM® 2 dual-density midsole </li>\r\n  <li>Merrell air cushion in the heel absorbs shock and adds stability </li>\r\n  <li>M Select™ GRIP tunes each outsole with durable traction that grips when and where you need it </li>\r\n</ul>', '4900.00', 2, 'assets/img/products/merrel-womens-siren-q2-strap-sandal\r\n.jpg', 'Merrel Women\'s Siren Q2 Strap Sandal', 'Merrel Women\'s Siren Q2 Strap Sandal gives you support, alignment and stability, so you can forge your own path and embrace the great outdoors!', 'merrel, siren, siren q2, strap sandal, sandal, hiking sandal', 1, '2018-01-26 20:55:42'),
(21, 'Merrel Men\'s Moab FST Hiking Shoes', 'M-0035769', '<p>The Moab FST waterproof is the best hiking shoe and gives you the confidence to follow our own path.</p>', '<p>This hiker will keep you comfortable on long treks through diverse environments and offers great support and fit thanks to the Merrell M Select™ FIT.ECO+ blended EVA contoured footbed. Moab Fit + Superior Traction (FTS) will give you the dependability you expect, as well as modern athletic styling and a lighter midsole.</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Moulded nylon arch shank</li>\r\n  <li>Updated, modern styling with leather/mesh and TPU cage with a 3D print upper</li>\r\n  <li>The footbed also comes with organic odour control for long days</li>\r\n  <li>Debris is kept out by the bellows tongue to keep your feet clean and dry with traditional lace closure</li>\r\n  <li>Air cushioning in the heel to absorb shock and provide more stability over rough terrain </li>\r\n  <li>5 mm lug depth </li>\r\n</ul>', '5000.00', 3, 'assets/img/products/merrel-mens-moab-fst-hiking-shoes.jpg', 'Merrel Men\'s Moab FST Hiking Shoes', 'Merrel Men\'s Moab FST Hiking Shoes waterproof is the best hiking shoe and gives you the confidence to follow our own path.', 'waterproof, hiking shoe, moab, moab fst, merrel', 1, '2018-01-26 21:02:11'),
(22, 'Merrel Charm 7 Limit Hiking Shoe - Dusty Olive', 'M-0012781', '<p> This protective hiker features durable suede and breathable ventilation so you can push your limits, no matter the distance.</p>', '<p> This protective hiker features durable suede and breathable ventilation so you can push your limits, no matter the distance.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Dusty Olive</p>\r\n<p><strong>Weight: </strong> 916 g</p>\r\n<p><strong>Lug Depth: </strong> 4 mm</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Pig suede leather and mesh upper </li>\r\n  <li>Traditional lace closure </li>\r\n  <li>Bellows tongue keeps debris out </li>\r\n  <li>Protective rubber toe cap </li>\r\n  <li>Breathable mesh lining </li>\r\n  <li>EVA removable footbed </li>\r\n  <li>Merrell Air Cushion in the heel absorbs shock and adds stability </li>\r\n  <li>EVA midsole for stability and comfort </li>\r\n  <li>Molded nylon arch shank</li>\r\n  <li>Flex Index Grade 2 </li>\r\n  <li>M Select™ GRIP outsole tunes each outsole with durable traction that grips when and where you need it</li>\r\n</ul>', '8200.00', 5, 'assets/img/products/merrel-charm-7-limit-hiking-shoe---dusty-olive.jpg', 'Merrel Charm 7 Limit Hiking Shoe - Dusty Olive', 'Merrel Charm 7 Limit Hiking Shoe - Dusty Olive features durable suede and breathable ventilation so you can push your limits, no matter the distance.', 'merrel, charm 7 limit, hiking shoe,  charm 7', 1, '2018-01-26 21:08:40'),
(23, 'Craghoppers Men\'s Kiwi Long Jacket Parka Green / Dark Khaki', 'CMP261-R24', '<p>Providing a little extra coverage - thanks to its longer length - this 3-in-1 jacket offers reliable waterproof protection with the added comfort of a zip-out fleece inner.</p>', '<p>Kiwi is synonymous with practical protection and this year-round performer is no exception. The classic outer jacket delivers reliable waterproof coverage, while the detachable fleece provides warmth - either as a companion layer or a standalone cover-up.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Fabrics: </strong> 100% polyester</p>\r\n<p><strong>Color: </strong> Parka Green / Dark Khaki</p>\r\n<p><strong>Weight: </strong> 1535 g</p>\r\n<p class=\"orange\"><strong>Please refer to the images for the sizing guide</strong></p>\r\n<img src=\"assets/img/catalog/craghoppers-sizing-guide.jpg\" class=\"img-responsive\">', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>AquaDry</li>\r\n  <li>Waterproof</li>\r\n  <li>Microfleece</li>\r\n  <li>Breathable </li>\r\n  <li>5 pockets</li>\r\n  <li>100% Polyester</li>\r\n  <li>1535 g</li>\r\n  <li>EVA midsole for stability and comfort </li>\r\n</ul>', '9900.00', 3, 'assets/img/products/craghoppers-men-s-kiwi-long-jacket-parka-green-dark-khaki.jpg', 'Craghoppers Men\'s Kiwi Long Jacket Parka Green / Dark Khaki', 'Craghoppers Men\'s Kiwi Long Jacket Parka Green / Dark Khaki offers reliable waterproof protection with the added comfort of a zip-out fleece inner.', 'Craghoppers, mens jacket, kiwi jacket, kiwi long jacket, parka jacket', 1, '2018-01-26 21:26:48'),
(24, 'Craghoppers Men\'s Berwyn Jacket Black', 'CML057-800-L', '<p>Looking for a sporty softshell jacket that offers reliable protection in cooler conditions? Berwyn fits the bill, featuring streamlined two-tone styling and a weather-resistant finish for versatile performance. </p>', '<p>The soft-brushed fleecy inner face adds extra warmth, while the windproof outer stops the breeze in its tracks. A superb all-season softshell for active wear, whatever the weather. </p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Black</p>\r\n<img src=\"assets/img/catalog/craghoppers-sizing-guide.jpg\" class=\"img-responsive\">\r\n<p class=\"orange\"><strong>Please refer to the images for the sizing guide</strong></p>\r\n<img src=\"assets/img/catalog/craghoppers-sizing-guide.jpg\" class=\"img-responsive\">', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Softshell</li>\r\n  <li>Smartdry</li>\r\n  <li>Insulating</li>\r\n  <li>Wash &amp; Wear</li>\r\n  <li>Security</li>\r\n</ul>', '5700.00', 3, 'assets/img/products/craghoppers-men-s-berwyn-jacket-black.jpg', 'Craghoppers Men\'s Berwyn Jacket Black ', 'Craghoppers Men\'s Berwyn Jacket Black features streamlined two-tone styling and a weather-resistant finish for versatile performance.', 'craghoppers, berwyn, berwyn jacket, softshell jacket', 1, '2018-01-26 21:30:59'),
(25, 'Craghoppers Men\'s Kiwi Interactive Jacket Black', 'CMA1135R-B-L', '<p>Our fabulously practical microfleece jacket is a great standalone but is also designed to interact perfectly with Kiwi Jackets, providing a handy extra layer of insulation when it is needed.</p>', '<p>Constructed from top quality, fast drying, lightweight fleece fabric, it incorporates snug handwarmer pockets and a full length. The classic fleece for everyday adventures.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Black</p>\r\n<p class=\"orange\"><strong>Please refer to the images for the sizing guide</strong></p>\r\n<img src=\"assets/img/catalog/craghoppers-sizing-guide.jpg\" class=\"img-responsive\">', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Wash &amp; Wear</li>\r\n  <li>Lightweight</li>\r\n  <li>Full length interactive zip</li>\r\n  <li>2 welted zipped lower pockets</li>\r\n</ul>', '3300.00', 9, 'assets/img/products/craghoppers-men-s-kiwi-interactive-jacket-black.jpg', 'Craghoppers Men\'s Kiwi Interactive Jacket Black', 'Our fabulously practical microfleece jacket is a great standalone but is also designed to interact perfectly with Kiwi Jackets, providing a handy extra layer of insulation when it is needed.', 'craghoppers, kiwi jacket, kiwi, microfleece jacket', 1, '2018-01-26 21:43:12'),
(26, 'Ferrino Hervey Pants Man Antracite', '20058N04', '<p>Slim fit trekking pants in Stretch fabric. Ultra-light, small size and fast-drying. The ideal garment for heavy-duty travel. Belt with fast release buckle included.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Antracite</p>\r\n<p><strong>Weight: </strong> 420 grams</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>HL GETDRY BISTRETCH: Polyamide 85% - elastan 15% - Weight 150 g per m2.</li>\r\n  <li>Fast drying</li>\r\n  <li>UV protection (UPF 40+)</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Elastic inserts</li>\r\n  <li>Waist pockets</li>\r\n  <li>2 leg pockets </li>\r\n  <li>Preformed knees </li>\r\n  <li>Adjustable leg hem </li>\r\n  <li>Back pockets</li>\r\n  <li>Travel pocket </li>\r\n</ul>', '5000.00', 7, 'assets/img/products/ferrino-hervey-pants-man-antracite.jpg', 'Ferrino Hervey Pants Man Antracite', 'Ferrino Hervey Pants Man Antracite is the ideal garment for heavy-duty travel. Belt with fast release buckle included.', 'ferrino, hervey, hervey pants, mens pants', 1, '2018-01-26 21:50:11'),
(27, 'Ferrino Samburu Pants Woman Antracite', '21252G04', '<p>Pants for trekking in a mono stretch fabric and minimal design. Perfect also for travelling because of a quick dry treatment and anti UV protection.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Antracite</p>\r\n<p><strong>Weight: </strong> 280 grams</p>', '<strong><p class=\"orange\">Features</p></strong>\r\n<ul>\r\n  <li>Rear pocket with zip</li>\r\n  <li>Knee pocket with zip</li>\r\n  <li>Front pockets with zip</li>\r\n  <li>Quick dry and anti UV UPF 50+ treatments</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>HL monostretch 55% Rayon, 38% Nylon, 7% Elastan</li>\r\n</ul>', '3700.00', 2, 'assets/img/products/ferrino-samburu-pants-woman-antracite.jpg', 'Ferrino Samburu Pants Woman Antracite', 'Ferrino Samburu Pants Woman Antracite is the best pants for trekking in a mono stretch fabric and minimal design. ', 'trekking pants, ferrino, samburu, samburu pants', 1, '2018-01-26 21:54:14'),
(28, 'Ferrino Rotor Hoodie Jacket Man Steel', '20832H36', '<p>Sweatshirt with zip and hood. Double front pocket featuring rotor logo. Rear silk printing with stylized logo.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Steel</p>\r\n<p><strong>Weight: </strong> 670 grams</p>\r\n<p><strong>Size: </strong> M</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>100% Cotton</li>\r\n  <li>20% Polyester</li>\r\n</ul>', '3400.00', 2, 'assets/img/products/ferrino-rotor-hoodie-jacket-man-steel.jpg', 'Ferrino Rotor Hoodie Jacket Man Steel', 'Ferrino Rotor Hoodie Jacket Man Steel is a sweatshirt with zip and hood. Double front pocket featuring rotor logo. Rear silk printing with stylized logo.', 'ferrino, rotor, rotor hoodie, rotor jacket, sweatshirt', 1, '2018-01-26 21:58:31'),
(29, 'Ferrino Tent Shaba 4', '92032DBA', '<p>A range of roomy, comfortable tents with large vestibule and additional removable floor</p>', '<p>Maximum comfort for minimum space. High and roomy tent with many pockets and a wide front vestibule. The ideal solution for those who love to camp but don’t want renounce comfort</p>\r\n\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Blue</p>\r\n<p><strong>Weight: </strong> 7000 grams</p>\r\n<p><strong>Dimensions: </strong> 24x58 cm</p>\r\n<p><strong>Capacity: </strong> 4 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly-sheet in thermal insulating, aluminised polyester</li>\r\n  <li>Inner tent in water-repellent, breathable cotton-nylon</li>\r\n  <li>Floor in thermal insulating polyester</li>\r\n  <li>Taped seams on fly-sheet and floor </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>3 shock corded duraluminium poles</li>\r\n  <li>Pre-formed vestibule pole for increased living space</li>\r\n  <li>Steel pegs</li>\r\n  <li>Inner tent overhung on poles with hooks for fast set-up and sleeves on the ridge </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>2 vestibules</li>\r\n  <li>Doors with mosquito net</li>\r\n  <li>Ventilation outlets</li>\r\n  <li>Raisable snow flap</li>\r\n  <li>“Air” ventilation system for inner tent </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>Additional, removable floor for living area</li>\r\n  <li>F.A. guy line adjustment</li>\r\n  <li>Vestibule arch pole in different colour for easier set-up</li>\r\n  <li>Lamp hook</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n</ul>', '17700.00', 2, 'assets/img/products/ferrino-tent-shaba-4.jpg', 'Ferrino Tent Shaba 4', 'A range of roomy, comfortable tents with large vestibule and additional removable floor. ', 'ferrino, shaba, tent, shaba tent, comfortable tent, camping tent', 3, '2018-01-26 22:44:24'),
(30, 'Ferrino Lightent  Tent 1 FR Red', '91144CRFR', '<p>A real example of light weight and reliability. Equipped with two pre-formed poles in duraluminium to increase the living space in the inner tent.</p>', '<p>A real example of light weight and reliability. Equipped with two pre-formed poles in duraluminium to increase the living space in the inner tent.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Red</p>\r\n<p><strong>Maximum Weight: </strong> 1450 grams</p>\r\n<p><strong>Minimum Weight: </strong> 1300 grams</p>\r\n<p><strong>Dimensions: </strong> 13x33 cm</p>\r\n<p><strong>Capacity: </strong> 1 person</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly sheet in thermal insulating, aluminised Ripstop Polyester, waterproof to 3,000mm</li>\r\n  <li>Floor in thermal insulating aluminised waterproof polyester to 3,000mm</li>\r\n  <li>Mosquito net inner</li>\r\n  <li>Taped seams on fly sheet and floor</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>2 shock-corded poles in duraluminium</li>\r\n  <li>Inner tent with continuous overhanging sleeves</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Mosquito net door</li>\r\n  <li>Ventilation outlets</li>\r\n  <li>“Air” ventilation system</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>Quick adjusting guy lines</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Lamp hook</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n  <li>Aluminium pegs</li>\r\n</ul>', '8800.00', 2, 'assets/img/products/ferrino-lightent--tent-1-fr-red.jpg', 'Ferrino Lightent  Tent 1 FR Red', 'Ferrino Lightent  Tent 1 FR Red is a real example of light weight and reliability. ', 'ferrino, tent, lightweight tent, lightent, lightent 1', 3, '2018-01-26 22:53:30'),
(31, 'Ferrino Sintesi 1 Olive Green', '91174DVO', '<p>Ferrino proposes a new series of 1 and 2 person tents intended for users requiring an ultra light tent with no compromises.</p>', '<p>Ferrino proposes a new series of 1 and 2 person tents intended for users requiring an ultra light tent with no compromises.</p>\r\n<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Olive Green</p>\r\n<p><strong>Maximum Weight: </strong> 990 grams</p>\r\n<p><strong>Minimum Weight: </strong> 830 grams</p>\r\n<p><strong>Dimensions: </strong> 14x30 cm</p>\r\n<p><strong>Capacity: </strong> 1 person</p>\r\n', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Single walled tent in Ripstop 50D 3000 mm polyester FR treatment with mosquito net inside FR treated.</li>\r\n  <li>Floor in waterproof polyester &#40;3000 mm&#41; with FR treatment</li>\r\n  <li>Taped seams on fly-sheet and floor</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>Exernal poles</li>\r\n  <li>3 pre-formed duraluminium poles in different colours for easy setup</li>\r\n  <li>Exagon aluminium pegs</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Mosquito net door</li>\r\n  <li>Vestibule</li>\r\n  <li>Front ventilation</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>F.A. guy line</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Lamp hook</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n</ul>', '8100.00', 3, 'assets/img/products/ferrino-sintesi-1-olive-green.jpg', 'Ferrino Sintesi 1 Olive Green', 'Ferrino Sintesi 1 Olive Green is intended for users requiring an ultra light tent with no compromises.</p>', 'ferrino sintersi 1, light tent, tent sintesi tent, camping tent', 3, '2018-01-26 22:59:41'),
(32, 'Ferrino Leaf 2 Lightweight Tent', '91196', '<p>Tent designed for those needing a lightweight tent for backpacking. Light, robust, and comfy, thanks to the innovative shape that increases living space around the inner tent ridge</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Orange</p>\r\n<p><strong>Maximum Weight: </strong> 2500 grams</p>\r\n<p><strong>Minimum Weight: </strong> 2350 grams</p>\r\n<p><strong>Dimensions: </strong> 15x43 cm</p>\r\n<p><strong>Capacity: </strong> 2 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly-sheet in Ripstop polyester &#40;3000 mm&#41; with FR treatment</li>\r\n  <li>Inner tent in mosquito net and polyester ripstop 70D fabric with FR treatment</li>\r\n  <li>Floor in FR polyester, waterproof to 3000 mm</li>\r\n  <li>Taped seams on fly-sheet and floor </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>3 pre-formed duraluminium poles in different colours for easy setup</li>\r\n  <li>Inner tent overhung on poles with hooks for quick set-up</li>\r\n  <li>“Hexagon” aluminium pegs </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Vestibules</li>\r\n  <li>Mosquito net doors </li>\r\n  <li>Ventilation outlets </li>\r\n  <li>“Camera air” ventilation system </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>F.A. guy line</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>“Ambient light” inner pockets</li>\r\n  <li>Lamp hook</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n</ul>', '13300.00', 1, 'assets/img/products/ferrino-leaf-2-lightweight-tent.jpg', 'Ferrino Leaf 2 Lightweight Tent', 'Ferrino Leaf 2 Lightweight Tent is designed for those needing a lightweight tent for backpacking. ', 'ferrino, tent, lightweight tent, leaf tent', 3, '2018-01-26 23:10:09'),
(33, 'Ferrino Phantom 2 Tent', '91172BBB', '<p>Line of light tents for two or three persons which guarantee excellent living space and ventilation because of the duraluminium structure with ridge pole and double entrance with front and back vestibules.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Blue</p>\r\n<p><strong>Maximum Weight: </strong> 2300 grams</p>\r\n<p><strong>Minimum Weight: </strong> 2100 grams</p>\r\n<p><strong>Dimensions: </strong> 14x36 cm</p>\r\n<p><strong>Capacity: </strong> 2 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly-sheet in Ripstop polyester &#40;3000 mm&#41; with FR treatment</li>\r\n  <li>Inner tent in FR mosquito net</li>\r\n  <li>Floor in FR polyester, waterproof to 3000 mm</li>\r\n  <li>Taped seams on fly-sheet and floor </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>3 pre-formed duraluminium poles in different colours for easy setup</li>\r\n  <li>Inner tent overhung on poles with hooks</li>\r\n  <li>Exagon aluminium pegs </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Vestibules</li>\r\n  <li>Doors with external mosquito net, which open fully can be stored in the special pocket</li>\r\n  <li>Ventilation outlets </li>\r\n  <li>Air ventilation system for inner tent</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>F.A. guy line</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Lamp hook</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n</ul>', '12200.00', 2, 'assets/img/products/ferrino-phantom-2-tent.jpg', 'Ferrino Phantom 2 Tent', 'Ferrino Phantom 2 Tent is a line of light tents for two or three persons which guarantee excellent living space and ventilation.', 'ferrino, phantom, phantom 2, tent, phantom 2 tent', 3, '2018-01-26 23:16:09');
INSERT INTO `products` (`product_ID`, `product_name`, `sku`, `short_description`, `long_description`, `features`, `price`, `quantity`, `image`, `meta_title`, `meta_description`, `meta_keyword`, `category_ID`, `date_created`) VALUES
(34, 'Ferrino Chaos 2 Olive Green Tent', '91147VOFR', '<p> Central pole with aluminium alloy joints: a shock-corded support structure solidarised to the joints for an inner tent with more stability and volume and incredibly easy to set up. </p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Olive Green</p>\r\n<p><strong>Maximum Weight: </strong> 2400 grams</p>\r\n<p><strong>Minimum Weight: </strong> 2200 grams</p>\r\n<p><strong>Dimensions: </strong> 16x38 cm</p>\r\n<p><strong>Capacity: </strong> 2 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly sheet in Ripstop polyester, waterproof to 3,000mm</li>\r\n  <li>Mosquito net inner with inserts in water-repellent, breathable Textile H.T.</li>\r\n  <li>Floor in polyester, waterproof to 3,000mm</li>\r\n  <li>Taped seams on fly sheet and floor</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>Supporting structure with shock-corded duraluminium poles and radial joints</li>\r\n  <li>Inner tent overhung on poles with hooks</li>\r\n  <li>Duraluminium ridge pole in a different colour for easy identification</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>2 Entrances</li>\r\n  <li>1 Vestibule</li>\r\n  <li>Fully opening mosquito net doors</li>\r\n  <li>Ventilation outlets</li>\r\n  <li>“Air” ventilation system</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>Quick adjusting guy lines</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Lamp hook</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n  <li>Aluminium pegs</li>\r\n</ul>', '14000.00', 2, 'assets/img/products/ferrino-chaos-2-olive-green-tent.jpg', 'Ferrino Chaos 2 Olive Green Tent', 'Ferrino Chaos 2 Olive Green Tent is an easy to set up tent with more stability and volume.', 'Ferrino, chaos, chaos 2', 3, '2018-01-26 23:23:22'),
(35, 'Ferrino Lightent 2 Tent - Olive Green', '91145WMFR', '<p>A real example of light weight and reliability. Equipped with two pre-formed poles in duraluminium to increase the living space in the inner tent.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Olive Green</p>\r\n<p><strong>Maximum Weight: </strong> 1850 grams</p>\r\n<p><strong>Minimum Weight: </strong> 1650 grams</p>\r\n<p><strong>Dimensions: </strong> 17x35 cm</p>\r\n<p><strong>Capacity: </strong> 2 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly sheet in thermal insulating, aluminised Ripstop Polyester, waterproof to 3,000mm</li>\r\n  <li>Floor in thermal insulating aluminised waterproof polyester to 3,000mm</li>\r\n  <li>Mosquito net inner</li>\r\n  <li>Taped seams on fly sheet and floor</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>2 shock-corded poles in duraluminium</li>\r\n  <li>Inner tent with continuous overhanging sleeves</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Mosquito net door</li>\r\n  <li>Ventilation outlets</li>\r\n  <li>“Air” ventilation system</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>Quick adjusting guy lines</li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Lamp hook</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n  <li>Aluminium pegs</li>\r\n</ul>', '11100.00', 2, 'assets/img/products/ferrino-lightent-2-tent-olive-green.jpg\r\n', 'Ferrino Lightent 2 Tent - Olive Green', 'Ferrino Lightent 2 Tent - olive green is a real example of light weight and reliability. ', 'ferrino, lightent, lightent 2, light tent', 3, '2018-01-26 23:28:58'),
(36, 'Ferrino Bivy High Lab Tent', '99078', '<p>The Bivy HL tent is a single-canvas, ultra-light and compact bivy tent.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Orange</p>\r\n<p><strong>Maximum Weight: </strong> 1250 grams</p>\r\n<p><strong>Minimum Weight: </strong> 1100 grams</p>\r\n<p><strong>Dimensions: </strong> 11x35 cm</p>\r\n<p><strong>Capacity: </strong> 1 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Texit membrane waterproof to 4,000mm</li>\r\n  <li>Polyester floor waterproof to 8,000mm</li>\r\n  <li>Taped seams on fly sheet and floor</li>\r\n  <li>Triple reinforcement at floor corners</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>2 shock-corded poles in duraluminium</li>\r\n  <li>Fly sheet suspended from external poles with sleeves</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Front entrance</li>\r\n  <li>Front door with internal mosquito net</li>\r\n  <li>Stormproof ventilation outlets</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>Reflective quick adjusting guy lines</li>\r\n  <li>Stuff sack</li>\r\n  <li>Repair kit</li>\r\n  <li>Aluminium pegs</li>\r\n</ul>', '14900.00', 1, 'assets/img/products/ferrino-bivy-high-lab-tent.jpg', 'Ferrino Bivy High Lab Tent', 'Ferrino bivy high lab tent is a single-canvas, ultra-light and compact bivy tent.', 'ferrino, high lab tent, bivy, tent, lightweight tent', 3, '2018-01-26 23:36:13'),
(37, 'Ferrino Emperor 2 Tent', '99079', '<p>Emperor is the new frontier when it comes to the technology and performance achieved by Ferrino: the W.T.S. welding system is now used on expedition tents.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Color: </strong> Orange</p>\r\n<p><strong>Maximum Weight: </strong> 3100 grams</p>\r\n<p><strong>Minimum Weight: </strong> 2800 grams</p>\r\n<p><strong>Dimensions: </strong> 18x40 cm</p>\r\n<p><strong>Capacity: </strong> 2 persons</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly-sheet in TU laminated 40D x 40D 254T nylon, waterproof to 10,000mm</li>\r\n  <li>Inner tent in water-repellent and breathable Ripstop polyester</li>\r\n  <li>Floor in waterproof polyester</li>\r\n  <li>Polyurethane front window</li>\r\n  <li>Taped seams on floor</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>Single support frame with shock-corded aluminium poles and radial joints</li>\r\n  <li>Inner tent overhung on poles with hooks</li>\r\n  <li>Aluminium pegs</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>2 vestibules</li>\r\n  <li>2 fully opening door</li>\r\n  <li>Ventilation outlets</li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>Lamp hook</li>\r\n  <li>Quick adjusting guy lines</li>\r\n  <li>Repair kit</li>\r\n  <li>Compact stuff sack</li>\r\n</ul>', '31000.00', 3, 'assets/img/products/ferrino-emperor-2-tent.jpg', 'Ferrino Emperor 2 Tent', 'Ferrino Emperor 2 Tent is the new frontier when it comes to the technology and performance achieved by Ferrino: the W.T.S. welding system is now used on expedition tents.', 'ferrino, emperor, emperor 2, tent, camping tent', 3, '2018-01-26 23:44:41'),
(38, 'Ferrino Nemesi 1 Tent', '91166', '<p>A range of super-light tents made using FR fabrics, with solidarised duraluminium structure with radial joints and ridge pole to guarantee excellent comfort and easy set up.</p>', '<strong><p class=\"orange\">Specifications</p></strong>\r\n<p><strong>Maximum Weight: </strong> 1700 grams</p>\r\n<p><strong>Minimum Weight: </strong> 1500 grams</p>\r\n<p><strong>Dimensions: </strong> 13x34 cm</p>\r\n<p><strong>Capacity: </strong> 1 person</p>', '<strong><p class=\"orange\">Fabrics</p></strong>\r\n<ul>\r\n  <li>Fly-sheet in Ripstop polyester &#40;3000 mm&#41; </li>\r\n  <li>Inner tent in FR mosquito net </li>\r\n  <li>Floor in FR polyester, waterproof to 3000 mm </li>\r\n  <li>Taped seams on fly-sheet and floor </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Structure</p></strong>\r\n<ul>\r\n  <li>Supporting structure with shock-corded duraluminium poles and radial joint</li>\r\n  <li>Duraluminium ridge pole in a different colour</li>\r\n  <li>Inner tent overhung on poles with hooks </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Entrance and Ventilation</p></strong>\r\n<ul>\r\n  <li>Vestibule </li>\r\n  <li>Fully opening mosquito net doors </li>\r\n  <li>Ventilation outlets</li>\r\n  <li>“Camera Air” ventilation system </li>\r\n</ul>\r\n\r\n<strong><p class=\"orange\">Accessories</p></strong>\r\n<ul>\r\n  <li>F.A. guy line adjustment </li>\r\n  <li>Inside storage pockets</li>\r\n  <li>Lamp hook </li>\r\n  <li>Stuff sack </li>\r\n  <li>Repair kit </li>\r\n</ul>', '10000.00', 1, 'assets/img/products/ferrino-nemesi-1-tent.jpg', 'Ferrino Nemesi 1 Tent', 'A range of super-light tents made using FR fabrics, with solidarised duraluminium structure with radial joints and ridge pole to guarantee excellent comfort and easy set up.', 'ferrino, light tent, nemesi, nemesi 1', 3, '2018-01-26 23:52:05');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin_accounts`
--
ALTER TABLE `admin_accounts`
  ADD PRIMARY KEY (`admin_id`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `customers`
--
ALTER TABLE `customers`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `order_details`
--
ALTER TABLE `order_details`
  ADD PRIMARY KEY (`invoice_number`),
  ADD KEY `payment_id` (`payment_id`),
  ADD KEY `product_id` (`product_id`),
  ADD KEY `customers_id` (`customers_id`);

--
-- Indexes for table `payment_details`
--
ALTER TABLE `payment_details`
  ADD PRIMARY KEY (`payment_id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_ID`),
  ADD KEY `category_id` (`category_ID`) USING BTREE;

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin_accounts`
--
ALTER TABLE `admin_accounts`
  MODIFY `admin_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `customers`
--
ALTER TABLE `customers`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `order_details`
--
ALTER TABLE `order_details`
  MODIFY `invoice_number` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `payment_details`
--
ALTER TABLE `payment_details`
  MODIFY `payment_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `product_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `order_details`
--
ALTER TABLE `order_details`
  ADD CONSTRAINT `customers_id` FOREIGN KEY (`customers_id`) REFERENCES `customers` (`id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `payment_id` FOREIGN KEY (`payment_id`) REFERENCES `payment_details` (`payment_id`) ON UPDATE CASCADE,
  ADD CONSTRAINT `product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`product_ID`) ON UPDATE CASCADE;

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `category` FOREIGN KEY (`category_ID`) REFERENCES `categories` (`id`) ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
